### ISSUE TITLE
Why use two Embedding Layer

### ISSUE THREAD

**Issue by b3326023** [perrier1034/skipgram-word2vec-keras#2]
Excuse me, in skipgram_embedding.py, from line 63 to line 67, why did you use two Embedding Layer?
```
embedded_pvt = Embedding(input_dim=vocab_size,
                         output_dim=vec_dim,
                         input_length=1)(input_pvt)

embedded_ctx = Embedding(input_dim=vocab_size,
                         output_dim=vec_dim,
                         input_length=1)(input_ctx)
```
Shouldn't it only need one Embedding Layer? Like this:
```
embedding = Embedding(input_dim=vocab_size, output_dim=vec_dim, input_length=1)
embedded_pvt  = embedding(input_pvt)
embedded_ctx = embedding(input_ctx)
```

**Comment by raskr** [comment]
I think your implementation makes sense (more like better than mine?). Please try that.
And actually my negative-sampling implementation is not adaptive (parameterized), so you should refer any other implementations.
